name: flutter_workflows

packages:
  - data/**
  - domain/**
  - '*'

scripts:
  clean:
    run: melos exec flutter clean
    description: Clean all modules.

  pkget:
    run: melos exec flutter pub get
    description: Pull referenced packages in all modules.

  generate:
    run: melos exec flutter packages pub run build_runner build --delete-conflicting-outputs && flutter pub run intl_utils:generate
    description: Generate code files in all modules.

  init:
    run: melos run clean && melos run pkget && melos run generate
    description: Pull referenced packages and generate code files in all modules.

  analyze:
    run: melos exec flutter format --set-exit-if-changed . && flutter analyze .
    description: Run Flutter format & analyze in all modules.

  test:
    run: melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub
    description: Run Flutter tests in all modules.