name: ble_temperature
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.2
  flutter_bloc: ^8.1.2
  get_it: ^7.4.0
  async: ^2.10.0
  path_provider: ^2.0.15
  equatable: ^2.0.5
  material_design_icons_flutter: ^6.0.7096
  dartz: ^0.10.1
  url_launcher: ^6.1.11
  permission_handler: ^10.4.5
  geolocator: ^9.0.2
  device_info_plus: ^8.2.2
  flutter_reactive_ble: ^5.2.0
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/about_bg.jpg
    - assets/images/me.png

flutter_intl:
  enabled: true