name: ble_temperature
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.5+6

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  async: ^2.10.0
  dartz: ^0.10.1
  device_info_plus: ^11.1.1
  equatable: ^2.0.5
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_reactive_ble: ^5.2.0
  geolocator: ^13.0.2
  get_it: ^8.0.2
  intl: ^0.19.0
  intl_utils: ^2.8.2
  material_design_icons_flutter: ^7.0.7296
  mockito: ^5.4.2
  package_info_plus: ^8.1.1
  path_provider: ^2.0.15
  permission_handler: ^11.3.1
  url_launcher: ^6.1.14
  
dev_dependencies:
  build_runner: any
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/about_bg.jpg
    - assets/images/me.png

flutter_intl:
  enabled: true