name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.0.5

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  collection: ^1.17.0
  async: ^2.10.0
  mockito: ^5.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: any
  hive_generator: any
  freezed: ^2.3.3
  json_serializable: any
